### ISSUE TITLE
Add as official Hashids implementation for Nim?

### ISSUE THREAD

**Issue by jd327** [achesak/nim-hashids#1]
Hi. Not sure how else to get in touch with you, but would you like this repo added to the list of others as official for Nim?

**Comment by achesak** [comment]
Apologies for the late response.

I took some time and updated this to work with the latest version of Nim and follow Hashids 1.0 as best as possible. Some things don't quite follow the other implementations though; for example, I use a `createHashids` proc instead of an object constructor, simply because Nim doesn't support constructors with initialization code.

Here's an example usage in the same format as the others:

``` nimrod
var hashids : Hashids = createHashids("this is my salt")
var id : string = hashids.encode(@[1, 2, 3])
var numbers : seq[int] = hashids.decode(id)
```

**Comment by jd327** [comment]
That sounds good Adam. A few implementations differ in their own ways because of language restrictions/features. And we've just switched to 1.0 (from 0.3) a few months back, so as long as your ids match other implementations, should be good.

Still not sure tho if you'd like it added to the list of others on the website. I'd be glad to in case someone else finds your implementation useful. The updates to the lib are very rare, so I only ask maintainers to handle their own bugs if users open issues.

If you'd like that, just tell me. I'll update the documentation site @ http://hashids.org/

**Comment by achesak** [comment]
This completely slipped my mind until now, haha. Sure, I'd appreciate it if you'd add it to the site.

**Comment by jd327** [comment]
Cool, need a few quick things tho:

1) I'm not too familiar with Nim, could you give me a quick code snippet of encoding + decoding [1, 2, 3] so I could show it as an example? Something like this: http://hashids.org/javascript/#repo

2) If you use twitter and would like it linked, please tell me your username :]

**Comment by achesak** [comment]
Here's an example:

``` nimrod
var hashids : Hashids = createHashids("this is my salt")
var id : string = hashids.encode(@[1, 2, 3])
var numbers : seq[int] = hashids.decode(id)
```

It would also require a `import hashids` at the start, but only the Kotlin example has that so I'm not certain if you'd want to include it in the example or not.

Also I'm not on twitter, but a link to the repo would be nice.

**Comment by jd327** [comment]
Hehe, good catch about the import. I guess I should stay consistent.

Added your repo @ http://hashids.org/nim/ - thanks for the port! Also invited you to Hashids github group.
